# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

version = 1.0
group = creeperpookie.creeperprotect
mod_id = creeperprotect
name = CreeperProtect
archivesBaseName = creeperprotect
author = CreeperPookie
description = A simple mod to protect Creepers from harm :D
url = https://github.com/CreeperPookie/CreeperProtect

# The following properties are used to set the version of Minecraft and Forge that the mod is built against.

# The version of Minecraft that the mod is built against.
minecraft_version = 1.12.2

# The version of Forge that the mod is built against.
forge_version = 14.23.5.2860



